- name: Download and install K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server --disable servicelb --disable traefik
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start K3s service
  systemd:
    name: k3s
    enabled: yes
    state: started

- name: Create a directory if it doesn't exist
  file:
    path: /home/administrator/.kube/
    state: directory
    owner: administrator
    group: administrator
    mode: '0755'

- name: Copy Kubeconfig for the administrator user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/administrator/.kube/config
    remote_src: yes
    owner: administrator
    group: administrator
    mode: '0644'

- name: Replace 127.0.0.1 with {{ controller_ip }}in configuration file
  ansible.builtin.lineinfile:
    path: /home/administrator/.kube/config
    regexp: '127\.0\.0\.1'
    line: "{{ controller_ip }}"
    backup: yes