---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k3s-agent-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../.."
  inventory:
    group_vars:
      all:
        k3s_server_url: "https://127.0.0.1:6443"
        k3s_node_token: "test-token"
verifier:
  name: ansible
